AWSTemplateFormatVersion: "2010-09-09"
Description: Internet gateway to VPC with a single public subnet and some ECS resources to start a Docker container
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
