AWSTemplateFormatVersion: '2010-09-09'
Description:  Deploys a Docker container within a previously created VPC.
              Requires a running network stack.

Parameters:
  NetworkStackName:
    Type: String
    Description: Network stack name
    Default: an-example-stack
  ServiceName:
    Type: String
    Description: A human-readable name for the service
    Default: an-example-service-name
  ImageUrl:
    Type: String
    Description: URL of docker-image
  ContainerPort:
    Type: Number
    Description: xxx
    Default: 80
  ContainerCPU:
    Type: Number
    Description: How much CPU assigned to the container
    Default: 256
  ContainerMemory:
    Type: Number
    Description: How much memory assigned to the container
    Default: 512
  DesiredCount:
    Type: Number
    Description: Copies of the service task to be run
    Default: 1

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Ref ServiceName
      RetentionInDays: 1

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      Cpu: !Ref ContainerCPU
      Memory: !Ref ContainerMemory

